server:
  port: 9050

spring:
  application:
    name: pcmis-security
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: pcmis
        group: pcmis
      
feign:
  sentinel:
    enabled: true

