# 配置服务器端口和Tomcat相关参数
server:
  port: 9030
  tomcat:
    max-connections: 2048
    accept-count: 256
    threads:
      max: 64
      min-spare: 32
  compression:
    enabled: true

# Spring应用特定配置
spring:
  application:
    name: pcmis-visual
  cache:
    cache-names: user,case,project,risk,security,visual,file
    redis:
      cache-null-values: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: pcmis
        group: pcmis
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

# Feign客户端配置，启用Sentinel支持
feign:
  sentinel:
    enabled: true

# 异步任务执行器配置
async:
  executor:
    thread:
      core_pool_size: 4
      max_pool_size: 8
      queue_capacity: 200
      name_prefix: normal-pool-

# Minio（S3兼容）对象存储配置
# minio
s3:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin

