server:
  port: 9090

spring:
  application:
    name: pcmis-case
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: pcmis
        group: pcmis

feign:
  sentinel:
    enabled: true
